<a href="https://colab.research.google.com/github/srishti-parulekar/studyML/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

Ai is the ability of a computer to mimic human intelligence.
Machine learning enables computers to learn from data and make predictions.

ML process:
Data preprocesing (import data, clean the data and split into training and testing sets).
Modeling: build and train the model, make predictions.
Evaluation: calculate performance metrics.

Types of learning:
Supervised Learning:

What is feature scaling?
Feature scaling is always applied to columns, never to data inside the rows.
Two main types:
Normalisation and Standardization:

With normalising a column: each entry X is modified to become X - Xmin / Max - Min;
Each new column entry is now between the values 0 and 1.

Standardization: X - u / p where u is the average and p is the standard deviation. All the values mostly between [-3,3]

Feature scaling is necessary when grouping data values or clustering algorithms to check compatibility between values and the scale of the columns is drastically different so that the values can be normalised and one column wont overpower the other.

Dependent variables are the varaibles that you want your model to predict while independent variables or features are the variables that are given to the model and the model uses them to make the prediction.

We use the iloc function from pandas: stands for locate indexes. This allows us to split the columns or rows of the dataframe to create a new data frame.

Missing values can be replaced using SImpleImputer.

IMP: upper bound of range in python
The fit() method helps in fitting the data into a model, transform() method helps in transforming the data into a form that is more suitable for the model.

How do we encode categorical data?
If we encode the company names of India, France and Germany as 0,1,2 it may work for our operations but the model may assume that the ordering has some significance which is not the case, so this cannot be done as it could cause misinterpreted correlations.

We can do so by using binary vectors for the (independent variables)countries ( 1,0,0 and 0,1,0 and 0,0,1) and for binary values (0,1) for the (dependent) outcomes being yes and no.
This is done using One Hot Encoding.
Label encoding is being used for the binary value encoding of no and yes.
OneHotEncoder after transforming doesnt return a np array so that needs to be taken care of separately.

Do we perform feature scaling before or after splitting the data into training and testing sets? AFTER.
The test set is supposed to be a brand new set. The feature scaling takes the mean and the standard deviation of all values including the test set, there would be information leakage on the test set.

When to use standardisation and when to use normalisation?
Normalisation is great when you have a normal distribution in most of your features.
Standardisation is great always.

Do we have to apply feature scaling to the dummy variables in the matrix of features? NO.
Post standardisation all the values of the variables will be between -3 and 3. Since dummy variables have binary values of 0 and 1 already, they are already in range. Standardisation will make it worse since it will transform these values to be between -3 and 3 but we will lose the interpretation of these values that we need to train our model.

Delimiters used when the csv file has its row values separated by something other than commas,
Example if separated by ;
dataset = pd.read_csv('winequality-red.csv', sep=';')

Regression models (both linear and non-linear) are used for predicting a real value, like salary for example. If your independent variable is time, then you are forecasting future values, otherwise your model is predicting present but unknown values.

In [ ]:
import numpy as np
# numpy allows us to work with arrays
import matplotlib.pyplot as plt
# allows us to plot graphs, importing the pyplot module in specific
import pandas as pd
# good to preprocess datasets

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
# taking all the rows, and all the columns except the last column which is the dependent variable.
y = dataset.iloc[:, -1].values
# takes all the rows and only the last column
# X and y are numpy arrays necessarily so that the train() function can be applied on them.

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data!

In [ ]:
# for large datasets, you can just delete the rows that have missing data.
# not always efficient, can instead replace the missing data value.
# missing value can be replaced by average or by the median value of that column or something else too.

from sklearn.impute import SimpleImputer
#
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# creating imputer object with parameters stating which data values to replace with what strategy.
imputer.fit(X[:, 1:3])
# since in python upperbound is not included for column number 1 and 2: [1,3] is used.
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


One Hot Encoding


In [ ]:
# encoding the independent variable:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# transformer parameter contains the transformation that needs to be done: encoding, the class that will perform the encoding
# ie OneHotEncoder, the third element is the indexes of the column on which we want to perform the encoding,
# here it is the country column only.

# remainder is going to state that we want to keep the columns that we are not applying the transformation too as well.

X = np.array(ct.fit_transform(X))
# here ct.fit_transform() doesnt automatically return a numpy array

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


france is encoded as 1.0, 0.0, 0.0
germany as 0.0 0.0 1.0 and so on

Encode the dependent var

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into training and testing.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

# ensures that the same randomization is used each time you run the code, resulting in the same splits of the data.

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


Feature Scaling (always after Splitting!)

In [ ]:
# not always applied
# normalisation good when normal distribution for most of your features, standardisation is always good.

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [ ]:
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
# fit will just give the mean and the std dev of the columns, transform will actually change each entry in the column.
# by applying the formula.

In [ ]:
# we need to standardise the test values by the same scaler (ie using the calculated mean and std dev of the training set)
# and not its own scaler since that would cause information leakage,
# we already fitted sc with the scaler for the training set so we use the same values of mean and std dev
# and directly apply transform of the test set.
X_test[:,3:] = sc.transform(X_test[:,3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


# Simple Regression

In [ ]:
# Regression models (both linear and non-linear) are used for predicting a real value, like salary for example.
# If your independent variable is time, then you are forecasting future values, otherwise your model is predicting present but unknown values.